### ISSUE TITLE
Requested 1218 position is beyond length 235: Trying to seek beyond buffer at BufferCursor.seek 

### ISSUE THREAD

**Issue by xiaoqiang** [tjfontaine/node-dns#101]
events.js:72
        throw er; // Unhandled 'error' event
VError: Requested 1218 position is beyond length 235: Trying to seek beyond buffer
    at BufferCursor.seek (/private/var/folders/2q/yxt6jydd6tsf82yh6p5t12ym0000gn/T/.org.chromium.Chromium.AeS8FC/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:83:11)
    at BufferCursor.slice (/private/var/folders/2q/yxt6jydd6tsf82yh6p5t12ym0000gn/T/.org.chromium.Chromium.AeS8FC/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:130:8)
    at Function.Packet.parse (/private/var/folders/2q/yxt6jydd6tsf82yh6p5t12ym0000gn/T/.org.chromium.Chromium.AeS8FC/node_modules/native-dns/node_modules/native-dns-packet/packet.js:774:24)
    at Function.Packet.parse (/private/var/folders/2q/yxt6jydd6tsf82yh6p5t12ym0000gn/T/.org.chromium.Chromium.AeS8FC/node_modules/native-dns/lib/packet.js:48:15)
    at Server.handleMessage (/private/var/folders/2q/yxt6jydd6tsf82yh6p5t12ym0000gn/T/.org.chromium.Chromium.AeS8FC/node_modules/native-dns/lib/server.js:60:22)
    at Socket.<anonymous> (/private/var/folders/2q/yxt6jydd6tsf82yh6p5t12ym0000gn/T/.org.chromium.Chromium.AeS8FC/node_modules/native-dns/lib/server.js:80:10)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:441:8)

**Comment by ysle** [comment]
this issue is still there, but it's more likely about the native-dns-packet.
