### ISSUE TITLE
BufferCursorOverflow 

### ISSUE THREAD

**Issue by amit777** [tjfontaine/node-dns#104]
I'm not sure exactly how to reproduce this. I however see it in my logs occasionally.

```
VError: BufferCursorOverflow: length 12, position 12, size 1
    at new BufferCursor.BufferCursorOverflow (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:44:10)
    at BufferCursor._checkWrite (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:70:15)
    at BufferCursor._move (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:53:8)
    at BufferCursor.readUInt8 (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:210:8)
    at nameUnpack (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/packet.js:70:14)
    at parseQuestion (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/packet.js:525:14)
    at Function.Packet.parse (/home/centos/lookup/node_modules/native-dns/node_modules/native-dns-packet/packet.js:704:17)
    at Function.Packet.parse (/home/centos/lookup/node_modules/native-dns/lib/packet.js:48:15)
    at Server.handleMessage (/home/centos/lookup/node_modules/native-dns/lib/server.js:60:22)
    at Socket.<anonymous> (/home/centos/lookup/node_modules/native-dns/lib/server.js:80:10)
```

**Comment by cetinsert** [comment]
We had that happen in production as well!

```
VError: BufferCursorOverflow: length 40, position 39, size 4
    at new BufferCursor.BufferCursorOverflow (/home/smroberts/node_modules/dns-express/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:44:10)
    at BufferCursor._checkWrite (/home/smroberts/node_modules/dns-express/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:70:15)
    at BufferCursor._move (/home/smroberts/node_modules/dns-express/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:53:8)
    at BufferCursor.readUInt32BE (/home/smroberts/node_modules/dns-express/node_modules/native-dns/node_modules/native-dns-packet/node_modules/buffercursor/buffercursor.js:252:8)
    at parseRR (/home/smroberts/node_modules/dns-express/node_modules/native-dns/node_modules/native-dns-packet/packet.js:538:17)
    at Function.Packet.parse (/home/smroberts/node_modules/dns-express/node_modules/native-dns/node_modules/native-dns-packet/packet.js:731:17)
    at Function.Packet.parse (/home/smroberts/node_modules/dns-express/node_modules/native-dns/lib/packet.js:48:15)
    at Server.handleMessage (/home/smroberts/node_modules/dns-express/node_modules/native-dns/lib/server.js:60:22)
    at Socket.<anonymous> (/home/smroberts/node_modules/dns-express/node_modules/native-dns/lib/server.js:80:10)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)
⬢ dyn.dns
⬢ dyn.dns
```

**Comment by skippy1976** [comment]
note that the issue is with native-dns-packet rather than native-dns
