### ISSUE TITLE
Unhandled 'error' event in pending.js

### ISSUE THREAD

**Issue by mingshun** [tjfontaine/node-dns#43]
``` bash
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: getHostByName ETIMEOUT
    at SocketQueue._onclose (/root/ropi/node_modules/native-dns/lib/pending.js:201:9)
    at EventEmitter.emit (events.js:93:17)
    at Socket.TCPSocket.bind (/root/ropi/node_modules/native-dns/lib/utils.js:132:12)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.destroyed (net.js:358:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

When using dns request in tcp protocol, timeout causes this. It made the whole app crashed.
The exception caused from pending.js. Did I forget to catch the error or is the bug of node-dns?

**Comment by gramakri** [comment]
Looks like a very old issue but I had the same issue today with same call stack as https://github.com/tjfontaine/node-dns/issues/43#issuecomment-14704655

native-dns: 0.7.0
node: 4.1.1
