### ISSUE TITLE
TypeError: Cannot read property '_left' of null

### ISSUE THREAD

**Issue by redwoz** [tjfontaine/node-dns#78]
hi, im getting the following error when performing the initial request('native-dns'):

TypeError: Cannot read property '_left' of null
    at Heap.insert (/mnt/rw-a/node_modules/native-dns/node_modules/native-dns-cache/node_modules/binaryheap/binaryheap.js:68:16)
    at MemoryStoreExpire.set (/mnt/rw-a/node_modules/native-dns/node_modules/native-dns-cache/cache.js:78:17)
    at /mnt/rw-a/node_modules/native-dns/lib/platform.js:271:25
    at Array.forEach (native)
    at /mnt/rw-a/node_modules/native-dns/lib/platform.js:270:26
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

**Comment by liubida** [comment]
yes , i caught this error, either. i think it is the error with the binaryheap...

**Comment by josefzamrzla** [comment]
I went to the same issue when I had modified Array.prototype with method "equals": http://stackoverflow.com/a/14853974/1262210
After removal of this method, everything works again. Maybe it is your cause as well.
